version: "3.8"
services:
    server:
      build: .
      command: >
        sh -c "rm -rfv ./uploads/* && npm install && npm run dev"
      container_name: plugin-manager-api
      restart: always
      networks:
        - default
      env_file:
        - .env
      depends_on:
        - database
      ports:
        - 8000:8000
      volumes:
        - ./:/home/node/app
    database:
      container_name: pg_container
      image: postgres
      restart: always
      networks:
        - default      
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: teste
      ports:
        - "5432:5432"
    pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      networks:
        - default      
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: root@root.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"
    elasticsearch:
        container_name: es-container
        restart: always
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
        environment:
          - xpack.security.enabled=false
          - "discovery.type=single-node"
        networks:
          - es-net
        ports:
          - 9200:9200
    kibana:
      container_name: kb-container
      restart: always
      image: docker.elastic.co/kibana/kibana:7.11.0
      environment:
        - ELASTICSEARCH_HOSTS=http://es-container:9200
      networks:
        - es-net
      depends_on:
        - elasticsearch
      ports:
        - 5601:5601
    rabbitmq:
            image: rabbitmq:3-management-alpine
            container_name: rabbitmq
            volumes:
                - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
                - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
                - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
            env_file:
              - .env
            ports:
                - 5672:5672
                - 15672:15672
      
networks:
  es-net:
    driver: bridge