version: "3.8"
services:
    database:
      container_name: pg_container
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: teste
      ports:
        - "5432:5432"
    pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: root@root.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"
    server:
      build: .
      command: >
        sh -c "rm -rfv ./tmp/* && npm install && npm run dev"
      container_name: bootcamp-teste-api
      depends_on:
        - database
      ports:
        - 8000:8000
      volumes:
        - ./:/home/node/app
      links:
        - database
